name: Déploiement So-Close

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Afficher l’heure du build
        run: date

      - name: Vérification Markdown
        uses: DavidAnson/markdownlint-cli2-action@v15
        with:
          globs: "**/*.md"
        
      - name: Installer les dépendances
        run: npm install

      - name: Build le projet
        run: npm run build

      - name: Nettoyer /home/sigl
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            rm -rf /home/sigl/*
        
      - name: Construire et pousser l'image Docker
        run: |
          docker build -t ghcr.io/bombocato/so-close:${{ github.sha }} .
          docker push ghcr.io/bombocato/so-close:${{ github.sha }}

      - name: Copier le contenu du dossier dist via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          source: dist/*
          target: /home/sigl/
          strip_components: 1

      - name: Déployer vers /var/www/so-close
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo rm -rf /var/www/so-close/*
            sudo cp -r /home/sigl/* /var/www/so-close/

      - name: Vérification de la page déployée
        run: |
          curl -f http://so-close.groupe25.socra-sigl.fr || exit 1
